doc: adds documentation for `onCopy` parameter
igeligel/react-in-out-textarea pull request #108
Opened 2021-10-02 16:01 UTC by wsameer

2021-10-02 16:01 UTC, wsameer commented
@igeligel let me know if the description is good enough for you?

2021-10-03 15:21 UTC, igeligel requested changes

2021-10-03 15:21 UTC, igeligel commented on README.md
> +| onCopy | function | ❌ | A function you want to be called when you've copied the content of `InOutTextarea` |
I think it should be

```suggestion
| onCopy | function | ❌ | A function that is called when you have copied the content of `InOutTextarea`. |
```

2021-10-03 16:07 UTC, wsameer commented
@igeligel done!

2021-10-03 18:40 UTC, igeligel approved these changes
Hey @wsameer. Thanks for your contribution 👍 Would be nice if you could leave a star for the library.
I tagged this Pull Request with the necessary hacktoberfest labels, in case you are participating there. Thanks a lot, contributors like you make Open Source awesome 💯

I will also add you to the official contributor's list!

2021-10-03 18:41 UTC, merged

2021-10-03 18:41 UTC, igeligel commented
@all-contributors please add @wsameer for docs

2021-10-03 19:37 UTC, igeligel commented
@all-contributors please add @wsameer for docs

2021-10-03 19:37 UTC, igeligel commented
@all-contributors please add @wsameer for docs